name: Download Official 5eTools Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Cada lunes 02:00 UTC

permissions:
  contents: write

jobs:
  fetch_and_filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          rm -rf data/official
          mkdir -p data/official

      - name: Download official JSON files
        run: |
          BASE="https://5e.tools/data"
          curl -L "$BASE/class/class.json" -o data/official/class.json
          curl -L "$BASE/race/races.json" -o data/official/races.json
          curl -L "$BASE/spells/spells-phb.json" -o data/official/spells-phb.json
          curl -L "$BASE/spells/spells-xge.json" -o data/official/spells-xge.json
          curl -L "$BASE/item/items-dmg.json" -o data/official/items-dmg.json
          curl -L "$BASE/monster/monsters-mm.json" -o data/official/monsters-mm.json
          curl -L "$BASE/background/backgrounds.json" -o data/official/backgrounds.json
          curl -L "$BASE/feat/feats.json" -o data/official/feats.json
          curl -L "$BASE/condition/conditions.json" -o data/official/conditions.json
          curl -L "$BASE/spells/spells-tce.json" -o data/official/spells-tce.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data/official
          git diff --quiet && git diff --staged --quiet || git commit -m "Update 5eTools data (direct CDN)"
          git push || echo "No changes to push"
